name: Build afv-native

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf autoconf-archive automake libtool pkg-config libltdl-dev 
          cmake --version
      - name: Bootstrap vcpkg
        run: |
          ./vcpkg/bootstrap-vcpkg.sh -disableMetrics
      - name: Configure cmake
        run: |
          cmake -S . -B build/ -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
      - name: Build
        run: |
          cmake --build build/
  build-osx-arm:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup environment
        run: |
          brew install cmake pkg-config
          cmake --version
      - name: Bootstrap vcpkg
        run: |
          ./vcpkg/bootstrap-vcpkg.sh -disableMetrics
      - name: Configure cmake
        run: |
          cmake -S . -B build/ -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCMAKE_OSX_ARCHITECTURES=arm64 -DVCPKG_TARGET_TRIPLET=arm64-osx
      - name: Build
        run: |
          cmake --build build/
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup environment
        run: |
          cmake --version
      - name: Bootstrap vcpkg
        run: |
          ./vcpkg/bootstrap-vcpkg.bat -disableMetrics
      - name: Configure cmake
        run: |
          cmake -S . -B build/ -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
      - name: Build
        run: |
          cmake --build build/ --config ${{ env.BUILD_TYPE }}
